# Etapa 1: Instalación y build de dependencias
FROM node:18-alpine AS builder
WORKDIR /app

# Copiar los archivos de dependencias e instalarlas
COPY package*.json ./
RUN npm ci

# Copiar el resto del código y construir la aplicación Next.js
COPY . .
RUN npm run build

# Etapa 2: Imagen de producción
FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# Copiar archivos necesarios desde la etapa builder
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js ./

# Instalar solo las dependencias de producción
RUN npm ci --only=production

EXPOSE 3000
CMD ["npm", "start"]