# Usa la imagen oficial de Node.js (versión 18 en Alpine para imágenes ligeras)
FROM node:18-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /

# Copia los archivos de definición de dependencias y bloque de versiones
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos del proyecto al contenedor
COPY . .

# Expone el puerto en el que corre la aplicación (ajústalo según tu configuración)
EXPOSE 5002

# Comando por defecto para iniciar la aplicación
CMD ["npm", "start"]